# 3.1 넘파이 배열

In [1]:
import numpy as np

In [3]:
# 배열 생성
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [4]:
# 배열의 자료형
type(A)

numpy.ndarray

In [5]:
# 배열의 차원
A.ndim

2

In [6]:
# 배열의 크기
A.shape

(2, 2)

In [7]:
# 원소 자료형
A.dtype

dtype('int64')

In [8]:
# 원소별 최댓값, 평균값, 최솟값, 합계 구하는 함수
A.max(), A.mean(), A.min(), A.sum()

(4, 2.5, 1, 10)

In [9]:
# 배열의 접근
A[0] # A행렬의 1번째 행

array([1, 2])

In [10]:
A[1] # A행렬의 2번째 행

array([3, 4])

In [12]:
# 배열 원소에 접근
print(A[0][0], A[0][1]) # 1행 1열, 1행 2열 원소 출력
print(A[1][0], A[1][1]) # 2행 1열, 2행 2열 원소 출력

1 2
3 4


In [13]:
# 조건에 맞는 원소들만 인덱싱
A[A>1] # 1보다 큰 원소 출력

array([2, 3, 4])

In [14]:
# 배열 형태 바꾸기(주대각선을 기준으로 뒤바꾸는 것)
A.T # A.transpose()로 해도됨

array([[1, 3],
       [2, 4]])

In [15]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [16]:
# 배열 평탄화
A.flatten()

array([1, 2, 3, 4])

In [17]:
# 배열의 원소별 연산
A+A

array([[2, 4],
       [6, 8]])

In [18]:
A-A

array([[0, 0],
       [0, 0]])

In [19]:
A*A

array([[ 1,  4],
       [ 9, 16]])

In [20]:
A/A

array([[1., 1.],
       [1., 1.]])

In [22]:
# 브로드캐스팅: 넘파이에서는 행렬 크기가 달라도 연산 가능함 (크기가 작은 행렬을 확장시켜주므로)
A = np.array([[1,2], [3,4]])
B = np.array([10,100])

A*B

array([[ 10, 200],
       [ 30, 400]])

In [23]:
# 내적 구하기
B.dot(B)

10100

In [24]:
A.dot(B)

array([210, 430])